### ISSUE TITLE
Dependency without a license

### ISSUE THREAD

**Issue by vogievetsky** [markbao/speakeasy#32]
Hi, I have noticed that one of your dependancies ezcrypto@0.0.3 https://github.com/ElmerZhang/ezcrypto does not have a license attached to it.

I have created and issue on their repo asking to add a license file: https://github.com/ElmerZhang/ezcrypto/issues/4

Your code has an MIT license which is great, but unfortunately if you depend on code with no license it can not really be MIT code (say ezcrypto claims their code is GPLv3 tomorrow). That code is technically proprietary (by default). See: https://stackoverflow.com/questions/1190628/what-license-is-public-code-under-if-no-license-is-specified

Please help me in reaching out to ElmerZhang or consider picking a permissive licensed alternative.

**Comment by markbao** [comment]
@vogievetsky Vadim, Thank you for bringing this to my attention and opening an issue in ElmerZhang's repo. Just now, Elmer added a license to his repo and marked it as MIT licensed, so we're clear to continue using it as a dependency. Thanks for taking the action!

**Comment by vogievetsky** [comment]
@markbao thank you for looking into this so quickly. Closing the issue.
