### ISSUE TITLE
replace ezcrypto with buffer?

### ISSUE THREAD

**Issue by coolaj86** [markbao/speakeasy#41]
Is there a reason for not using node's built-in buffer?

```
var digest_bytes = ezcrypto.util.hexToBytes(digest);
// instead of
var digest_bytes = new Buffer(digest, 'hex');
```

Also, I see a few places where you appear to be converting from hex to a binary string instead of using buffer, but then you immediately convert it to a buffer.

Would you be open to some cleanup of this code? Or where you doing it that way for a particular reason?

**Comment by markbao** [comment]
Thanks, @coolaj86. Closed thanks to #33.
